apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'opar-backend'
        static_configs:
          - targets: ['opar-backend-service.backends.svc.cluster.local:8081']

    rule_files:
      - '/etc/prometheus/alert.rules.yml' 

  alert.rules.yml: |
    groups:
      - name: http-alerts
        rules:
          - alert: HighHTTPRequests
            expr: rate(requests_total[1m]) * 100 > 5
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "Alta tasa de peticiones"
              description: "La cantidad de peticiones ha excedido en los últimos 60 segundos."
