apiVersion: apps/v1
kind: Deployment
metadata:
  name: opar-backend-deployment
  namespace: backends
  labels:
    app: opar-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opar-backend
  template:
    metadata:
      labels:
        app: opar-backend
    spec:
      containers:
      - name: opar-backend
        image: juliancastillo14/opar-backend:v1
        ports:
        - containerPort: 8081
        env:
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: database
        - name: MYSQL_DB_HOST
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: host
        - name: MYSQL_DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: username 
        - name: MYSQL_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: password
        - name: MYSQL_DB_PORT
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: port
---
apiVersion: v1
kind: Service
metadata:
  name: opar-backend-service
  namespace: backends
spec:
  type: NodePort
  selector:
    app: opar-backend
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30200
---

