services:
  db-opar:
    image: mysql:9.1
    container_name: db-opar
    environment:
      MYSQL_DB_USERNAME: root
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: opar
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"
  backend-opar:
    image: juliancastillo14/opar-backend:v2
    container_name: backend-opar
    depends_on:
      - db-opar
    environment:
      MYSQL_DB_USERNAME: root
      MYSQL_DB_PASSWORD: password
      MYSQL_DATABASE: opar
      MYSQL_DB_HOST: db-opar
      MYSQL_DB_PORT: 3306
    ports:
      - "8081:8081"
    links:
      - db-opar

  prometheus:
    image: prom/prometheus:v2.35.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana-data:/var/lib/grafana
volumes:
  db-data:
  grafana-data: